include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = RunningDotIndicatorPrefs

RunningDotIndicatorPrefs_FILES = MKRootListController.m
RunningDotIndicatorPrefs_INSTALL_PATH = /Library/PreferenceBundles
RunningDotIndicatorPrefs_FRAMEWORKS = UIKit
RunningDotIndicatorPrefs_PRIVATE_FRAMEWORKS = Preferences
RunningDotIndicatorPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
